#!/usr/bin/python

import pickle
import pandas as pd

enron_data = pickle.load(open("../final_project/final_project_dataset.pkl", "rb"))
df= pd.DataFrame.from_dict(enron_data).transpose()

print("Length of the Enron data set is: ", len(enron_data))

n = [x for x in enron_data.values() if x['poi'] == True]
print("Number of POIs equalling true: ", len(n))

m = [y for y in enron_data.values() if y['email_address'] != 'NaN' ]
print("Number of people with known email address: ", len(m))

p = [z for z in enron_data.values() if z['salary'] != 'NaN']
print("Number of people with known salary: ", len(p))

poi_name_record = open("../final_project/poi_names.txt").read().split("\n")
poi_name_total = [record for record in poi_name_record if "(y)" in record or "(n)" in record]
print("Total number of POIs: ", len(poi_name_total))

print("James Prentice's stock value: ", enron_data["PRENTICE JAMES"]["total_stock_value"])

print("Wesley Colwell emails to POIs: ", enron_data["COLWELL WESLEY"]["from_this_person_to_poi"])

print("Jeffrey Skilling value of stock options: ", enron_data["SKILLING JEFFREY K"]["exercised_stock_options"])
